name: scan branch
on:
  push:
    branches:
      - '**'

env:
  PYTHONPATH: src
  FASTCITK: ${{ secrets.FASTCITK }}
  IFASTCI: ${{ secrets.IFASTCI }}

jobs:

  ghcr_runner:
    runs-on: ubuntu-latest
    steps:
    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.FASTCITK }}

    - name: Pull image
      run: docker pull ghcr.io/quantum-rlk/islimci:1.0 

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Scan branch
      run: |
        docker run --rm \
        -v ${{ github.workspace }} : .github/rc \
        -w .github/rc \
        ghcr.io/quantum-rlk/islimci:1.0 \
        bash -c "
        ls -la
        python3.14 --version
        python3.14 xcicd-bscanner.py ${{ github.repository }} ${{ github.ref }} "XY-214$ǜéTK"
        "

    - name: Notify Slack on failure
      if: ${{ failure() }}
      uses: slackapi/slack-github-action@v2
      with:
        webhook: ${{ secrets.FASTCI_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "❌ GitHub Actions job failed",
            "blocks": [
              {
                "type": "section",
                "text": {
                "type": "mrkdwn",
                "text": "❌ *Scan job failed*\n*Repo:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Workflow:* ${{ github.workflow }}\n*Run:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              }
            ]
          }

    # - name: Scan branch
    #   id: scan_as
    #   run: python3.10 .github/rc/branchscanner.py QSB 
    #   continue-on-error: true

    # - name: Dump corrupted branch
    #   if: ${{ steps.scan_as.outcome != 'success' && github.ref != 'refs/heads/main' }}
    #   run: python .github/rc/branchdeleter.py ${{ github.repository }} ${{ github.ref }} ${{ secrets.FRTK }}
